version: '3.4'

networks:
  dislocknet:
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  houston:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/houston:/usr/data"
    environment:
      - WHOAMI=houston
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    depends_on:
      - lmhouston
      - lmparis
      - lmsingapore
    cap_add:
      - NET_ADMIN
    container_name: houston
    networks:
      dislocknet:
        ipv4_address: 172.21.0.51
    ports:
      - 6001:6000
    command: go run .

  paris:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/paris:/usr/data"
    environment:
      - WHOAMI=paris
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    depends_on:
      - lmhouston
      - lmparis
      - lmsingapore
    cap_add:
      - NET_ADMIN
    container_name: paris
    networks:
      dislocknet:
        ipv4_address: 172.21.0.52
    ports:
      - 6002:6000
    command: go run .

  singapore:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/singapore:/usr/data"
    environment:
      - WHOAMI=singapore
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    depends_on:
      - lmhouston
      - lmparis
      - lmsingapore
    cap_add:
      - NET_ADMIN
    container_name: singapore
    networks:
      dislocknet:
        ipv4_address: 172.21.0.53
    ports:
      - 6003:6000
    command: go run .


  lmhouston:
    build:
      context: ./lockmanager
      dockerfile: Dockerfile
    volumes:
      - "./lockmanager:/usr/app"
      - "./lockdata/houston:/usr/data"
    environment:
      - WHEREAMI=houston
    cap_add:
      - NET_ADMIN
    container_name: lmhouston
    networks:
      dislocknet:
        ipv4_address: 172.21.0.61
    ports:
      - 8001:8000
    command: go run .

  lmparis:
    build:
      context: ./lockmanager
      dockerfile: Dockerfile
    volumes:
      - "./lockmanager:/usr/app"
      - "./lockdata/paris:/usr/data"
    environment:
      - WHEREAMI=paris
    cap_add:
      - NET_ADMIN
    container_name: lmparis
    networks:
      dislocknet:
        ipv4_address: 172.21.0.62
    ports:
      - 8002:8000
    command: go run .

  lmsingapore:
    build:
      context: ./lockmanager
      dockerfile: Dockerfile
    volumes:
      - "./lockmanager:/usr/app"
      - "./lockdata/singapore:/usr/data"
    environment:
      - WHEREAMI=singapore
    cap_add:
      - NET_ADMIN
    container_name: lmsingapore
    networks:
      dislocknet:
        ipv4_address: 172.21.0.63
    ports:
      - 8003:8000
    command: go run .


  etcd-houston:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd-houston
    networks:
      dislocknet:
        ipv4_address: 172.21.0.81
    ports:
      - 2379
    volumes:
      - etcd-houston:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-houston
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-houston:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.81:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.81:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-houston:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-houston-cluster
      - ETCD_INITIAL_CLUSTER=etcd-houston=http://etcd-houston:2380
      - ETCD_INITIAL_CLUSTER_STATE=new


  etcd-paris:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd-paris
    networks:
      dislocknet:
        ipv4_address: 172.21.0.82
    ports:
      - 2379
    volumes:
      - etcd-paris:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-paris
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-paris:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.82:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.82:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-paris:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-paris-cluster
      - ETCD_INITIAL_CLUSTER=etcd-paris=http://etcd-paris:2380
      - ETCD_INITIAL_CLUSTER_STATE=new


  etcd-singapore:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd-singapore
    networks:
      dislocknet:
        ipv4_address: 172.21.0.83
    ports:
      - 2379
    volumes:
      - etcd-singapore:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-singapore
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-singapore:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.83:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.83:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-singapore:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-singapore-cluster
      - ETCD_INITIAL_CLUSTER=etcd-singapore=http://etcd-singapore:2380
      - ETCD_INITIAL_CLUSTER_STATE=new


volumes:
  etcd-houston:
  etcd-paris:
  etcd-singapore:
