version: '3.4'

networks:
  dislocknet:
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  houston:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/houston:/usr/data"
    environment:
      - WHOAMI=houston
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    cap_add:
      - NET_ADMIN
    container_name: houston
    networks:
      dislocknet:
        ipv4_address: 172.21.0.51
    ports:
      - 6001:6000
    command: go run .

  paris:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/paris:/usr/data"
    environment:
      - WHOAMI=paris
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    cap_add:
      - NET_ADMIN
    container_name: paris
    networks:
      dislocknet:
        ipv4_address: 172.21.0.52
    ports:
      - 6002:6000
    command: go run .

  singapore:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/singapore:/usr/data"
    environment:
      - WHOAMI=singapore
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    cap_add:
      - NET_ADMIN
    container_name: singapore
    networks:
      dislocknet:
        ipv4_address: 172.21.0.53
    ports:
      - 6003:6000
    command: go run .


  etcd0:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd0
    networks:
      dislocknet:
        ipv4_address: 172.21.0.41
    ports:
      - 2379
    volumes:
      - etcd0:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd0:2379
      - -listen-client-urls
      - http://172.21.0.41:2379
      - -initial-advertise-peer-urls
      - http://etcd0:2380
      - -listen-peer-urls
      - http://172.21.0.41:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  etcd1:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd1
    networks:
      dislocknet:
        ipv4_address: 172.21.0.42
    ports:
      - 2379
    volumes:
      - etcd1:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd1:2379
      - -listen-client-urls
      - http://172.21.0.42:2379
      - -initial-advertise-peer-urls
      - http://etcd1:2380
      - -listen-peer-urls
      - http://172.21.0.42:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  etcd2:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd2
    networks:
      dislocknet:
        ipv4_address: 172.21.0.43
    ports:
      - 2379
    volumes:
      - etcd2:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd2
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd2:2379
      - -listen-client-urls
      - http://172.21.0.43:2379
      - -initial-advertise-peer-urls
      - http://etcd2:2380
      - -listen-peer-urls
      - http://172.21.0.43:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380

volumes:
  etcd0:
  etcd1:
  etcd2:
