version: '3.4'

networks:
  dislocknet:
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  houston:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/houston:/usr/data"
    environment:
      - WHOAMI=houston
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    cap_add:
      - NET_ADMIN
    container_name: houston
    networks:
      dislocknet:
        ipv4_address: 172.21.0.51
    ports:
      - 6001:6000
    command: go run .

  paris:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/paris:/usr/data"
    environment:
      - WHOAMI=paris
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    cap_add:
      - NET_ADMIN
    container_name: paris
    networks:
      dislocknet:
        ipv4_address: 172.21.0.52
    ports:
      - 6002:6000
    command: go run .

  singapore:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/app"
      - "./data/singapore:/usr/data"
    environment:
      - WHOAMI=singapore
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - MODE=${MODE}
      - PLACEMENT=${PLACEMENT}
    cap_add:
      - NET_ADMIN
    container_name: singapore
    networks:
      dislocknet:
        ipv4_address: 172.21.0.53
    ports:
      - 6003:6000
    command: go run .


  etcd0-cent:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd0-cent
    networks:
      dislocknet:
        ipv4_address: 172.21.0.61
    ports:
      - 2379
    volumes:
      - etcd0-cent:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd0-cent
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd0-cent:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.61:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.61:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0-cent:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cent-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-cent=http://etcd0-cent:2380,etcd1-cent=http://etcd1-cent:2380,etcd2-cent=http://etcd2-cent:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
  etcd1-cent:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd1-cent
    networks:
      dislocknet:
        ipv4_address: 172.21.0.62
    ports:
      - 2379
    volumes:
      - etcd1-cent:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1-cent
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1-cent:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.62:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.62:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1-cent:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cent-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-cent=http://etcd0-cent:2380,etcd1-cent=http://etcd1-cent:2380,etcd2-cent=http://etcd2-cent:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
  etcd2-cent:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd2-cent
    networks:
      dislocknet:
        ipv4_address: 172.21.0.63
    ports:
      - 2379
    volumes:
      - etcd2-cent:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2-cent
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2-cent:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.63:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.63:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2-cent:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cent-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-cent=http://etcd0-cent:2380,etcd1-cent=http://etcd1-cent:2380,etcd2-cent=http://etcd2-cent:2380
      - ETCD_INITIAL_CLUSTER_STATE=new


  etcd0-clust:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd0-clust
    networks:
      dislocknet:
        ipv4_address: 172.21.0.71
    ports:
      - 2379
    volumes:
      - etcd0-clust:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd0-clust
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd0-clust:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.71:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.71:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0-clust:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-clust-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-clust=http://etcd0-clust:2380,etcd1-clust=http://etcd1-clust:2380,etcd2-clust=http://etcd2-clust:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
  etcd1-clust:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd1-clust
    networks:
      dislocknet:
        ipv4_address: 172.21.0.72
    ports:
      - 2379
    volumes:
      - etcd1-clust:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1-clust
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1-clust:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.72:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.72:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1-clust:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-clust-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-clust=http://etcd0-clust:2380,etcd1-clust=http://etcd1-clust:2380,etcd2-clust=http://etcd2-clust:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
  etcd2-clust:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd2-clust
    networks:
      dislocknet:
        ipv4_address: 172.21.0.73
    ports:
      - 2379
    volumes:
      - etcd2-clust:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2-clust
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2-clust:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.73:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.73:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2-clust:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-clust-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-clust=http://etcd0-clust:2380,etcd1-clust=http://etcd1-clust:2380,etcd2-clust=http://etcd2-clust:2380
      - ETCD_INITIAL_CLUSTER_STATE=new


  etcd0-dist:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd0-dist
    networks:
      dislocknet:
        ipv4_address: 172.21.0.81
    ports:
      - 2379
    volumes:
      - etcd0-dist:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd0-dist
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd0-dist:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.81:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.81:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0-dist:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-dist-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-dist=http://etcd0-dist:2380,etcd1-dist=http://etcd1-dist:2380,etcd2-dist=http://etcd2-dist:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
  etcd1-dist:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd1-dist
    networks:
      dislocknet:
        ipv4_address: 172.21.0.82
    ports:
      - 2379
    volumes:
      - etcd1-dist:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1-dist
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1-dist:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.82:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.82:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1-dist:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-dist-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-dist=http://etcd0-dist:2380,etcd1-dist=http://etcd1-dist:2380,etcd2-dist=http://etcd2-dist:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
  etcd2-dist:
    build:
      context: ./bitnami-docker-etcd/3/debian-10
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    container_name: etcd2-dist
    networks:
      dislocknet:
        ipv4_address: 172.21.0.83
    ports:
      - 2379
    volumes:
      - etcd2-dist:/etcd_data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2-dist
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2-dist:2380
      - ETCD_LISTEN_PEER_URLS=http://172.21.0.83:2380
      - ETCD_LISTEN_CLIENT_URLS=http://172.21.0.83:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2-dist:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-dist-cluster
      - ETCD_INITIAL_CLUSTER=etcd0-dist=http://etcd0-dist:2380,etcd1-dist=http://etcd1-dist:2380,etcd2-dist=http://etcd2-dist:2380
      - ETCD_INITIAL_CLUSTER_STATE=new


volumes:
  etcd0-cent:
  etcd1-cent:
  etcd2-cent:
  etcd0-clust:
  etcd1-clust:
  etcd2-clust:
  etcd0-dist:
  etcd1-dist:
  etcd2-dist:
